DROP DATABASE IF EXISTS DatLichKhamBenhBV;
CREATE DATABASE IF NOT EXISTS DatLichKhamBenhBV;
DROP USER IF EXISTS 'mta16211'@'localhost';
GRANT ALL PRIVILEGES ON DatLichKhamBenhBV.* TO 'mta16211'@'localhost' identified by 'hvktqsmta1621';
USE DatLichKhamBenhBV;
CREATE TABLE NHOMNGDUNG (
	MaNhomND VARCHAR(10),
	TenNhomND VARCHAR(100),
	PRIMARY KEY(MaNhomND)
);
CREATE TABLE NGUOIDUNG (
	MaTK VARCHAR(10),
	TenTK VARCHAR(20),
	MatKhau VARCHAR(50),
	MaNhomND VARCHAR(10),
	PRIMARY KEY(MaTK),
	FOREIGN KEY (MaNhomND) REFERENCES NHOMNGDUNG(MaNhomND)
);
CREATE TABLE KHOA (
	MaKhoa VARCHAR(10),
	TenKhoa VARCHAR(100),
	SoDT CHAR(10),
	PRIMARY KEY(MaKhoa)
);
CREATE TABLE BACSI (
	MaBS VARCHAR(10),
	TenBS VARCHAR(100),
	ChucVu VARCHAR(100),
	HocVi VARCHAR(100),
	HinhAnh VARCHAR(500),
	MaKhoa VARCHAR(10),
	MaTK VARCHAR(10),
	PRIMARY KEY(MaBS),
	FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa),
	FOREIGN KEY (MaTK) REFERENCES NGUOIDUNG(MaTK)
);
CREATE TABLE DICHVU (
	MaDV VARCHAR(10),
	TenDV VARCHAR(500) NOT NULL,
	DonGia DECIMAL(10, 2 ) NOT NULL,
	MaBS VARCHAR(10),
	PRIMARY KEY(MaDV),
	FOREIGN KEY (MaBS) REFERENCES BACSI(MaBS)
);
CREATE TABLE PHONGKHAM (
	MaBS VARCHAR(10),
	MaKhoa VARCHAR(10),
	SoPhong VARCHAR(10),
	PRIMARY KEY(MaBS, MaKhoa),
	FOREIGN KEY (MaBS) REFERENCES BACSI(MaBS),
	FOREIGN KEY (MaKhoa) REFERENCES KHOA(MaKhoa)
);
CREATE TABLE BENHNHAN (
	MaBN VARCHAR(10),
	HoTen VARCHAR(100),
	GioiTinh TINYINT NOT NULL CHECK(GioiTinh IN(0,1)),
	SoDT CHAR(10),
	Email VARCHAR(50),
	DiaChi VARCHAR(500),
	MaTK VARCHAR(10),
	PRIMARY KEY(MaBN),
	FOREIGN KEY (MaTK) REFERENCES NGUOIDUNG(MaTK)
);
CREATE TABLE LICHHEN (
	MaLichHen VARCHAR(10),
	ThoiGian VARCHAR(5), -- hh:mm
	NgayKham VARCHAR(10), -- DD-MM-YYYY
	GhiChu VARCHAR(500),
	TrangThai TINYINT NOT NULL CHECK(TrangThai IN(0,1)),
	MaBS VARCHAR(10),
	MaBN VARCHAR(10),
	PRIMARY KEY(MaLichHen),
	FOREIGN KEY (MaBS) REFERENCES BACSI(MaBS),
	FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN)
);
CREATE TABLE NGUOIDATLICH (
	MaNguoiDat VARCHAR(10),
	HoTen VARCHAR(100) NOT NULL,
	SoDT CHAR(10) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	MaBN VARCHAR(10),
	PRIMARY KEY(MaNguoiDat),
	FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN)
);
CREATE TABLE GOIKHAM (
	MaGK VARCHAR(10),
	TenGK VARCHAR(500) NOT NULL,
	DonGia DECIMAL(10, 2 ) NOT NULL,
	PRIMARY KEY(MaGK)
);
CREATE TABLE CHITIETDICHVU (
	MaGK VARCHAR(10),
	MaLichHen VARCHAR(10),
	ThoiGianDat TIMESTAMP,
	GhiChu VARCHAR(500),
	PRIMARY KEY(MaGK, MaLichHen),
	FOREIGN KEY (MaGK) REFERENCES GOIKHAM(MaGK),
	FOREIGN KEY (MaLichHen) REFERENCES LICHHEN(MaLichHen)
);